### ISSUE TITLE
enviroment problem

### ISSUE THREAD

**Issue by xiaowo1996** [ASMIftekhar/VSGNet#20]
hello, how can i built enviroment in conda ,after i create a conda enviroment via
``
conda create -n vsgnet python=2
``
and i run the command  pip2 install -r requirements.txt
the erro always appear 
``
Collecting bcolz==1.2.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5c/4e/23942de9d5c0fb16f10335fa83e52b431bcb8c0d4a8419c9ac206268c279/bcolz-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    SSE2 detected
    AVX2 detected
    /tmp/easy_install-xKS492/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7f6684a5fb90>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w1RpmQ/bcolz/setup.py", line 234, in <module>
        cmdclass=LazyCommandClass(),
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 883, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1151, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1137, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-xKS492/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        return super(LazyCommandClass, self).__getitem__(key)
      File "/tmp/easy_install-xKS492/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
        cpu_info = cpuinfo.get_cpu_info()
      File "/tmp/easy_install-xKS492/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-xKS492/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-xKS492/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax

``
how can i built enviroment use  the project?

**Comment by ASMIftekhar** [comment]
Hello,
I think this problem is happening from the installation of bcolz. At this moment I can not dig more into this. Interestingly we do not actually need bcolz to run the current version of VSGNet. I updated requirements.txt accordingly. Please update your local repository and try to set up the environment again.

**Comment by Radleye** [comment]
> Hello,
> I think this problem is happening from the installation of bcolz. At this moment I can not dig more into this. Interestingly we do not actually need bcolz to run the current version of VSGNet. I updated requirements.txt accordingly. Please update your local repository and try to set up the environment again.
@ASMIftekhar thanks, after update the requirment.txt the probem is solved. and i have a question. run theis project needs to install python2 and pyhon3 simultaneously. why not just use  python3 as a enviroment?beacause python2 maybe too old

**Comment by ASMIftekhar** [comment]
Yes, you are correct, hopefully, I will update everything to python 3 soon and create a branch for that.
